/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CheckboxValidationSettings {
    'validationType'?: CheckboxValidationSettings.ValidationTypeEnum;
    'minSelection'?: number | null;
    'maxSelection'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validationType",
            "baseName": "validationType",
            "type": "CheckboxValidationSettings.ValidationTypeEnum"
        },
        {
            "name": "minSelection",
            "baseName": "minSelection",
            "type": "number"
        },
        {
            "name": "maxSelection",
            "baseName": "maxSelection",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CheckboxValidationSettings.attributeTypeMap;
    }
}

export namespace CheckboxValidationSettings {
    export enum ValidationTypeEnum {
        Minimum = <any> 'Minimum',
        Maximum = <any> 'Maximum',
        Absolute = <any> 'Absolute',
        Range = <any> 'Range'
    }
}
