/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EmbeddedCloneTemplateJsonRequest {
    'redirectUrl'?: string | null;
    'viewOption'?: EmbeddedCloneTemplateJsonRequest.ViewOptionEnum = EmbeddedCloneTemplateJsonRequest.ViewOptionEnum.PreparePage;
    'showSaveButton'?: boolean = true;
    'showPreviewButton'?: boolean = true;
    'showNavigationButtons'?: boolean = true;
    'linkValidTill'?: Date | null;
    'includeFormFieldValues'?: boolean = false;
    'locale'?: EmbeddedCloneTemplateJsonRequest.LocaleEnum = EmbeddedCloneTemplateJsonRequest.LocaleEnum.En;
    'showCreateButton'?: boolean = true;
    'showToolbar'?: boolean = false;
    'showTooltip'?: boolean = false;
    'onBehalfOf'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string"
        },
        {
            "name": "viewOption",
            "baseName": "viewOption",
            "type": "EmbeddedCloneTemplateJsonRequest.ViewOptionEnum"
        },
        {
            "name": "showSaveButton",
            "baseName": "showSaveButton",
            "type": "boolean"
        },
        {
            "name": "showPreviewButton",
            "baseName": "showPreviewButton",
            "type": "boolean"
        },
        {
            "name": "showNavigationButtons",
            "baseName": "showNavigationButtons",
            "type": "boolean"
        },
        {
            "name": "linkValidTill",
            "baseName": "linkValidTill",
            "type": "Date"
        },
        {
            "name": "includeFormFieldValues",
            "baseName": "includeFormFieldValues",
            "type": "boolean"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "EmbeddedCloneTemplateJsonRequest.LocaleEnum"
        },
        {
            "name": "showCreateButton",
            "baseName": "showCreateButton",
            "type": "boolean"
        },
        {
            "name": "showToolbar",
            "baseName": "showToolbar",
            "type": "boolean"
        },
        {
            "name": "showTooltip",
            "baseName": "showTooltip",
            "type": "boolean"
        },
        {
            "name": "onBehalfOf",
            "baseName": "onBehalfOf",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EmbeddedCloneTemplateJsonRequest.attributeTypeMap;
    }
}

export namespace EmbeddedCloneTemplateJsonRequest {
    export enum ViewOptionEnum {
        PreparePage = <any> 'PreparePage',
        FillingPage = <any> 'FillingPage'
    }
    export enum LocaleEnum {
        En = <any> 'EN',
        No = <any> 'NO',
        Fr = <any> 'FR',
        De = <any> 'DE',
        Es = <any> 'ES',
        Bg = <any> 'BG',
        Cs = <any> 'CS',
        Da = <any> 'DA',
        It = <any> 'IT',
        Nl = <any> 'NL',
        Pl = <any> 'PL',
        Pt = <any> 'PT',
        Ro = <any> 'RO',
        Ru = <any> 'RU',
        Sv = <any> 'SV',
        Default = <any> 'Default',
        Ja = <any> 'JA',
        Th = <any> 'TH',
        ZhCn = <any> 'ZH_CN',
        ZhTw = <any> 'ZH_TW',
        Ko = <any> 'KO'
    }
}
