/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class KbaSettings {
    'type'?: KbaSettings.TypeEnum;
    'maximumRetryCount'?: number | null;
    'nameMatcher'?: KbaSettings.NameMatcherEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "KbaSettings.TypeEnum"
        },
        {
            "name": "maximumRetryCount",
            "baseName": "maximumRetryCount",
            "type": "number"
        },
        {
            "name": "nameMatcher",
            "baseName": "nameMatcher",
            "type": "KbaSettings.NameMatcherEnum"
        }    ];

    static getAttributeTypeMap() {
        return KbaSettings.attributeTypeMap;
    }
}

export namespace KbaSettings {
    export enum TypeEnum {
        None = <any> 'None',
        EveryAccess = <any> 'EveryAccess',
        UntilSignCompleted = <any> 'UntilSignCompleted',
        OncePerDocument = <any> 'OncePerDocument'
    }
    export enum NameMatcherEnum {
        None = <any> 'None',
        Lenient = <any> 'Lenient',
        Moderate = <any> 'Moderate',
        Strict = <any> 'Strict'
    }
}
