/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TemplateTeamShareRequest {
    'teamId': string;
    'action': TemplateTeamShareRequest.ActionEnum;
    'accessLevel'?: TemplateTeamShareRequest.AccessLevelEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "TemplateTeamShareRequest.ActionEnum"
        },
        {
            "name": "accessLevel",
            "baseName": "accessLevel",
            "type": "TemplateTeamShareRequest.AccessLevelEnum"
        }    ];

    static getAttributeTypeMap() {
        return TemplateTeamShareRequest.attributeTypeMap;
    }
}

export namespace TemplateTeamShareRequest {
    export enum ActionEnum {
        Grant = <any> 'Grant',
        Revoke = <any> 'Revoke'
    }
    export enum AccessLevelEnum {
        Use = <any> 'Use',
        Edit = <any> 'Edit'
    }
}
