/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookActorDetails } from './webhookActorDetails';

export class WebhookContext {
    'eventType'?: WebhookContext.EventTypeEnum;
    'actor'?: WebhookActorDetails;
    'previousState'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "WebhookContext.EventTypeEnum"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "WebhookActorDetails"
        },
        {
            "name": "previousState",
            "baseName": "previousState",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return WebhookContext.attributeTypeMap;
    }
}

export namespace WebhookContext {
    export enum EventTypeEnum {
        Sent = <any> 'Sent',
        Signed = <any> 'Signed',
        Completed = <any> 'Completed',
        Declined = <any> 'Declined',
        Revoked = <any> 'Revoked',
        Reassigned = <any> 'Reassigned',
        Expired = <any> 'Expired',
        Viewed = <any> 'Viewed',
        AuthenticationFailed = <any> 'AuthenticationFailed',
        DeliveryFailed = <any> 'DeliveryFailed',
        Verification = <any> 'Verification',
        SendFailed = <any> 'SendFailed',
        DraftCreated = <any> 'DraftCreated',
        SenderIdentityCreated = <any> 'SenderIdentityCreated',
        SenderIdentityUpdated = <any> 'SenderIdentityUpdated',
        SenderIdentityDeleted = <any> 'SenderIdentityDeleted',
        SenderIdentityRevoked = <any> 'SenderIdentityRevoked',
        SenderIdentityVerified = <any> 'SenderIdentityVerified',
        SenderIdentityDenied = <any> 'SenderIdentityDenied',
        TemplateCreated = <any> 'TemplateCreated',
        TemplateCreateFailed = <any> 'TemplateCreateFailed',
        TemplateDraftCreated = <any> 'TemplateDraftCreated',
        TemplateSendFailed = <any> 'TemplateSendFailed',
        IdentityVerificationInitiated = <any> 'IdentityVerificationInitiated',
        IdentityVerificationSucceeded = <any> 'IdentityVerificationSucceeded',
        IdentityVerificationFailed = <any> 'IdentityVerificationFailed',
        Reminder = <any> 'Reminder',
        Edited = <any> 'Edited',
        EditFailed = <any> 'EditFailed',
        TemplateEdited = <any> 'TemplateEdited',
        SignerSaved = <any> 'SignerSaved',
        KbaInitiated = <any> 'KBAInitiated',
        KbaSucceeded = <any> 'KBASucceeded',
        KbaFailed = <any> 'KBAFailed'
    }
}
