/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentEvent } from './documentEvent';
import { IWebhookData } from './iWebhookData';
import { WebhookContext } from './webhookContext';
import { WebhookEventMetadata } from './webhookEventMetadata';

export class WebhookEvent {
    'event'?: WebhookEventMetadata;
    'context'?: WebhookContext;
    'data'?: IWebhookData | null;
    'document'?: DocumentEvent;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "WebhookEventMetadata"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "WebhookContext"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "IWebhookData"
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "DocumentEvent"
        }    ];

    static getAttributeTypeMap() {
        return WebhookEvent.attributeTypeMap;
    }
}

